<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Common\Dto\" />
    <Folder Include="Common\Exceptions\" />
    <Folder Include="Extensions\Product-Service\Brand-Service\Queries\GetById\" />
    <Folder Include="Extensions\Product-Service\Category-service\Command\Delete\" />
    <Folder Include="Extensions\Product-Service\Category-service\Command\Update\" />
    <Folder Include="Extensions\Product-Service\Category-service\Queries\GetAll\" />
    <Folder Include="Extensions\Product-Service\Category-service\Queries\GetById\" />
    <Folder Include="Extensions\Product-Service\Product\" />
    <Folder Include="Features\Account-Service\" />
    <Folder Include="Features\Products-Service\Brands - Copy\Command\Create\" />
    <Folder Include="Features\Products-Service\Brands - Copy\Command\Delete\" />
    <Folder Include="Features\Products-Service\Brands - Copy\Command\Update\" />
    <Folder Include="Features\Products-Service\Brands - Copy\Queries\GetAllQuery\" />
    <Folder Include="Features\Products-Service\Brands - Copy\Queries\GetbyIdQuery\" />
    <Folder Include="Features\Products-Service\Brands\Command\Create\" />
    <Folder Include="Features\Products-Service\Brands\Command\Delete\" />
    <Folder Include="Features\Products-Service\Brands\Command\Update\" />
    <Folder Include="Features\Products-Service\Brands\Queries\GetAllQuery\" />
    <Folder Include="Features\Products-Service\Brands\Queries\GetbyIdQuery\" />
    <Folder Include="Features\Website-Service\" />
    <Folder Include="Features\Order-Service\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
    <ProjectReference Include="..\Shared\Shared.csproj" />
  </ItemGroup>

</Project>
